version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '4000:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /api/node_modules
      - ./api:/api
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /client/node_modules
      - ./client:/client
